management:
  endpoints:
    web:
      # Default (prod-safe). Can be overridden by env var or profile files.
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE:health}

springdoc:
  api-docs:
    # OFF by default (prod-safe). Can be overridden below or by env.
    enabled: ${OPENAPI_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

spring:
  devtools:
    restart:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  application:
    name: notice-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:unknown}

  r2dbc:
    url: r2dbc:postgresql://localhost:6543/notice-db
    username: user
    password: pass
    pool:
      initial-size: 2
      max-size: 10
#  flyway:
#    enabled: true
#    locations:
#      - classpath:db/migration
#      - classpath:com.example.notice_service.database.migration
#    baseline-on-migrate: true
#    url: jdbc:postgresql://localhost:6543/notice-db
#    password: pass
#    user: user

logging:
  level:
    org.flywaydb: DEBUG
