spring:
  application:
    name: notice-service
  r2dbc:
    url: r2dbc:postgresql://localhost:6543/notice-db
    username: user
    password: pass
    pool:
      initial-size: 2
      max-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:6543/notice-db
    password: pass
    user: user

logging:
  level:
    org.flywaydb: DEBUG